import { chromium } from 'playwright-core'
const EDGE = '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'
const browser = await chromium.launch({ executablePath: EDGE, headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://127.0.0.1:3080', { waitUntil: 'networkidle', timeout: 30000 })
await page.waitForTimeout(2500)
await page.getByText('新会话', { exact: false }).first().click()
await page.waitForTimeout(2500)
await page.getByText('月芒霜鳍鲸', { exact: true }).nth(1).click()
await page.waitForTimeout(2000)
await page.getByText('远程', { exact: true }).click()
await page.waitForTimeout(1500)
const text = await page.evaluate(() => document.body.innerText)
const idx = text.indexOf('远程服务器')
console.log('远程视图片段:\n', text.slice(idx, idx + 300))
await page.screenshot({ path: '/tmp/panel-view-remote.png' })
await browser.close()
